In [38]:
data = load('ex1data2.txt');
X = data(:, 1:2);
y = data(:, 3);
m = length(y);

In [39]:
data

data =

     2104        3   399900
     1600        3   329900
     2400        3   369000
     1416        2   232000
     3000        4   539900
     1985        4   299900
     1534        3   314900
     1427        3   198999
     1380        3   212000
     1494        3   242500
     1940        4   239999
     2000        3   347000
     1890        3   329999
     4478        5   699900
     1268        3   259900
     2300        4   449900
     1320        2   299900
     1236        3   199900
     2609        4   499998
     3031        4   599000
     1767        3   252900
     1888        2   255000
     1604        3   242900
     1962        4   259900
     3890        3   573900
     1100        3   249900
     1458        3   464500
     2526        3   469000
     2200        3   475000
     2637        3   299900
     1839        2   349900
     1000        1   169900
     2040        4   314900
     3137        3   579900
     1811        4   285900
     1437   

In [21]:
fprintf('First 10 examples from the dataset: \n');
fprintf(' x = [%.0f %.0f], y = %.0f \n', [X(1:10,:) y(1:10,:)]');

First 10 examples from the dataset: 
 x = [2104 3], y = 399900 
 x = [1600 3], y = 329900 
 x = [2400 3], y = 369000 
 x = [1416 2], y = 232000 
 x = [3000 4], y = 539900 
 x = [1985 4], y = 299900 
 x = [1534 3], y = 314900 
 x = [1427 3], y = 198999 
 x = [1380 3], y = 212000 
 x = [1494 3], y = 242500 


In [40]:
X_norm = X;
mu = zeros(1, size(X, 2));
sigma = zeros(1, size(X, 2));

In [41]:
X_norm

X_norm =

   2104      3
   1600      3
   2400      3
   1416      2
   3000      4
   1985      4
   1534      3
   1427      3
   1380      3
   1494      3
   1940      4
   2000      3
   1890      3
   4478      5
   1268      3
   2300      4
   1320      2
   1236      3
   2609      4
   3031      4
   1767      3
   1888      2
   1604      3
   1962      4
   3890      3
   1100      3
   1458      3
   2526      3
   2200      3
   2637      3
   1839      2
   1000      1
   2040      4
   3137      3
   1811      4
   1437      3
   1239      3
   2132      4
   4215      4
   2162      4
   1664      2
   2238      3
   2567      4
   1200      3
    852      2
   1852      4
   1203      3



In [42]:
sigma  = std(X_norm)

sigma =

   794.70235     0.76098



In [43]:
mu = mean(X_norm)

mu =

   2000.6809      3.1702



In [56]:
b = (X_norm .- mu) ./ sigma;

In [48]:
for i = 1:size(X, 2)
    mu1(i) = mean(X(:,i));
    sigma1(i) = std(X(:,i));
    a(:,i) = (X(:,i) - mu1(i));
    X_norm1(:,i) = (X(:,i) - mu1(i)) / sigma1(i);
end

In [50]:
X_norm1

X_norm1 =

   0.13000987  -0.22367519
  -0.50418984  -0.22367519
   0.50247636  -0.22367519
  -0.73572306  -1.53776691
   1.25747602   1.09041654
  -0.01973173   1.09041654
  -0.58723980  -0.22367519
  -0.72188140  -0.22367519
  -0.78102304  -0.22367519
  -0.63757311  -0.22367519
  -0.07635670   1.09041654
  -0.00085674  -0.22367519
  -0.13927334  -0.22367519
   3.11729182   2.40450826
  -0.92195631  -0.22367519
   0.37664309   1.09041654
  -0.85652301  -1.53776691
  -0.96222296  -0.22367519
   0.76546791   1.09041654
   1.29648433   1.09041654
  -0.29404827  -0.22367519
  -0.14179001  -1.53776691
  -0.49915651  -0.22367519
  -0.04867338   1.09041654
   2.37739217  -0.22367519
  -1.13335621  -0.22367519
  -0.68287309  -0.22367519
   0.66102629  -0.22367519
   0.25080981  -0.22367519
   0.80070123  -0.22367519
  -0.20344831  -1.53776691
  -1.25918949  -2.85185864
   0.04947657   1.09041654
   1.42986760  -0.22367519
  -0.23868163   1.09041654
  -0.70929808  -0.22367519
  -0.95844796  -0

ans =

   0.13000987  -0.22367519
  -0.50418984  -0.22367519
   0.50247636  -0.22367519
  -0.73572306  -1.53776691
   1.25747602   1.09041654
  -0.01973173   1.09041654
  -0.58723980  -0.22367519
  -0.72188140  -0.22367519
  -0.78102304  -0.22367519
  -0.63757311  -0.22367519
  -0.07635670   1.09041654
  -0.00085674  -0.22367519
  -0.13927334  -0.22367519
   3.11729182   2.40450826
  -0.92195631  -0.22367519
   0.37664309   1.09041654
  -0.85652301  -1.53776691
  -0.96222296  -0.22367519
   0.76546791   1.09041654
   1.29648433   1.09041654
  -0.29404827  -0.22367519
  -0.14179001  -1.53776691
  -0.49915651  -0.22367519
  -0.04867338   1.09041654
   2.37739217  -0.22367519
  -1.13335621  -0.22367519
  -0.68287309  -0.22367519
   0.66102629  -0.22367519
   0.25080981  -0.22367519
   0.80070123  -0.22367519
  -0.20344831  -1.53776691
  -1.25918949  -2.85185864
   0.04947657   1.09041654
   1.42986760  -0.22367519
  -0.23868163   1.09041654
  -0.70929808  -0.22367519
  -0.95844796  -0.223

In [57]:
size(b)

ans =

   47    2



In [58]:
function [X_norm, mu, sigma] = featureNormalize(X)
%FEATURENORMALIZE Normalizes the features in X
%   FEATURENORMALIZE(X) returns a normalized version of X where
%   the mean value of each feature is 0 and the standard deviation
%   is 1. This is often a good preprocessing step to do when
%   working with learning algorithms.

% You need to set these values correctly
X_norm = X;
mu = zeros(1, size(X, 2));
sigma = zeros(1, size(X, 2));

% ====================== YOUR CODE HERE ======================
% Instructions: First, for each feature dimension, compute the mean
%               of the feature and subtract it from the dataset,
%               storing the mean value in mu. Next, compute the
%               standard deviation of each feature and divide
%               each feature by it's standard deviation, storing
%               the standard deviation in sigma.
%
%               Note that X is a matrix where each column is a
%               feature and each row is an example. You need
%               to perform the normalization separately for
%               each feature.
%
% Hint: You might find the 'mean' and 'std' functions useful.
%

sigma  = std(X_norm);
mu = mean(X_norm);

X_norm = (X_norm .- mu) ./ sigma;




% ============================================================

end

In [59]:
[X_norm, mu, sigma] = featureNormalize(X)

X_norm =

   0.13000987  -0.22367519
  -0.50418984  -0.22367519
   0.50247636  -0.22367519
  -0.73572306  -1.53776691
   1.25747602   1.09041654
  -0.01973173   1.09041654
  -0.58723980  -0.22367519
  -0.72188140  -0.22367519
  -0.78102304  -0.22367519
  -0.63757311  -0.22367519
  -0.07635670   1.09041654
  -0.00085674  -0.22367519
  -0.13927334  -0.22367519
   3.11729182   2.40450826
  -0.92195631  -0.22367519
   0.37664309   1.09041654
  -0.85652301  -1.53776691
  -0.96222296  -0.22367519
   0.76546791   1.09041654
   1.29648433   1.09041654
  -0.29404827  -0.22367519
  -0.14179001  -1.53776691
  -0.49915651  -0.22367519
  -0.04867338   1.09041654
   2.37739217  -0.22367519
  -1.13335621  -0.22367519
  -0.68287309  -0.22367519
   0.66102629  -0.22367519
   0.25080981  -0.22367519
   0.80070123  -0.22367519
  -0.20344831  -1.53776691
  -1.25918949  -2.85185864
   0.04947657   1.09041654
   1.42986760  -0.22367519
  -0.23868163   1.09041654
  -0.70929808  -0.22367519
  -0.95844796  -0.